### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tancheng** [tancheng/VCGRA#1]
- [ ] Check how the `a[0:3] + b` looks like in vectorized LLVM IR in order to distinguish the vadder from the normal adder.
- [ ] Support `add_const` in `VectorAdderCombo`.
- [ ] Synthesize the generated SVerilog of `VectorAdderCombo`.
- [ ] Implement `VectorMultiplier`.
